"""
Script Generator — Generates Python scripts with actual column names baked in.
Scripts are saved to data/saved_analytics/ and reused on data-append runs.
"""
import json
import logging
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime

logger = logging.getLogger("analytics.script_generator")

SAVED_DIR = Path(__file__).parent.parent.parent / "data" / "saved_analytics"
MANIFEST_PATH = SAVED_DIR / "script_manifest.json"


def _get_col(mappings: Dict[str, str], semantic: str, fallback: str = "UNMAPPED") -> str:
    """Get actual column name from mappings with fallback."""
    return mappings.get(semantic, fallback)


def generate_kpi_script(column_mappings: Dict[str, Dict[str, str]], dataset_paths: Dict[str, str]) -> str:
    """
    Generate kpi_script.py with actual column names baked in.
    Returns the script content as a string.
    """
    cs = column_mappings.get("channel_summary", {})
    mo = column_mappings.get("monthly", {})
    us = column_mappings.get("user_summary", {})
    cu = column_mappings.get("channel_user", {})

    script = f'''#!/usr/bin/env python3
# AUTO-GENERATED by analytics_engine — {datetime.now().isoformat()}
# Column mappings baked in from column_mapper. Reused on data-append runs.
# DO NOT EDIT column assignments manually — regenerated on schema change.

import pandas as pd
import json
from pathlib import Path

# ─── Dataset paths ───────────────────────────────────────────────────────
DATASET_PATHS = {json.dumps(dataset_paths, indent=4)}

# ─── Column mappings (auto-generated) ────────────────────────────────────
# channel_summary columns
CS_CHANNEL   = {repr(cs.get("channel_name", "Channel"))}
CS_UPLOADED  = {repr(cs.get("uploaded_count", "Uploaded Count"))}
CS_CREATED   = {repr(cs.get("created_count", "Created Count"))}
CS_PUBLISHED = {repr(cs.get("published_count", "Published Count"))}
CS_UPL_DUR   = {repr(cs.get("uploaded_duration", "Uploaded Duration (hh:mm:ss)"))}
CS_CRE_DUR   = {repr(cs.get("created_duration", "Created Duration (hh:mm:ss)"))}
CS_PUB_DUR   = {repr(cs.get("published_duration", "Published Duration (hh:mm:ss)"))}

# monthly columns
MO_MONTH     = {repr(mo.get("month_label", "Month"))}
MO_UPLOADED  = {repr(mo.get("monthly_uploaded", "Total Uploaded"))}
MO_CREATED   = {repr(mo.get("monthly_created", "Total Created"))}
MO_PUBLISHED = {repr(mo.get("monthly_published", "Total Published"))}

# user_summary columns
US_USER      = {repr(us.get("user_name", "User"))}

# channel_user columns
CU_CHANNEL   = {repr(cu.get("channel_name", "Channel"))}
CU_USER      = {repr(cu.get("user_name", "User"))}


def parse_duration_to_seconds(series):
    """Parse hh:mm:ss strings to total seconds. Handles hours > 99."""
    def _parse(s):
        try:
            s = str(s).strip()
            if not s or s == "nan":
                return 0
            parts = s.split(":")
            if len(parts) == 3:
                return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
            elif len(parts) == 2:
                return int(parts[0]) * 60 + int(parts[1])
            return 0
        except Exception:
            return 0
    return series.apply(_parse)


def compute_kpis():
    """Compute all KPI metrics. Returns dict of metrics."""
    metrics = []

    # ─── Load channel_summary ─────────────────────────────────────────
    cs_path = DATASET_PATHS.get("channel_summary")
    if cs_path and Path(cs_path).exists():
        df = pd.read_csv(cs_path, encoding="utf-8-sig")

        # Volume KPIs
        total_uploaded = int(pd.to_numeric(df[CS_UPLOADED], errors="coerce").sum())
        total_processed = int(pd.to_numeric(df[CS_CREATED], errors="coerce").sum())
        total_published = int(pd.to_numeric(df[CS_PUBLISHED], errors="coerce").sum())

        metrics.append({{"id": "total_uploaded",  "name": "Total Uploaded",  "value": total_uploaded,
                         "formatted": f"{{total_uploaded:,}}", "category": "volume",
                         "description": "Total videos uploaded by users"}})
        metrics.append({{"id": "total_processed", "name": "Total Processed", "value": total_processed,
                         "formatted": f"{{total_processed:,}}", "category": "volume",
                         "description": "Total clips created by AI"}})
        metrics.append({{"id": "total_published", "name": "Total Published", "value": total_published,
                         "formatted": f"{{total_published:,}}", "category": "volume",
                         "description": "Total clips published to platforms"}})

        # Conversion KPIs
        publish_rate = round((total_published / total_processed * 100), 2) if total_processed > 0 else 0
        metrics.append({{"id": "publish_rate", "name": "Publish Rate", "value": publish_rate,
                         "formatted": f"{{publish_rate}}%", "category": "conversion",
                         "description": "Percentage of processed clips published"}})

        # Efficiency KPIs
        amplification = round(total_processed / total_uploaded, 2) if total_uploaded > 0 else 0
        process_rate = round(total_processed / total_uploaded * 100, 2) if total_uploaded > 0 else 0
        metrics.append({{"id": "amplification_ratio", "name": "Amplification Ratio", "value": amplification,
                         "formatted": f"{{amplification}}x", "category": "efficiency",
                         "description": "Output clips per uploaded video"}})
        metrics.append({{"id": "process_rate", "name": "Process Rate", "value": process_rate,
                         "formatted": f"{{process_rate}}%", "category": "efficiency",
                         "description": "Processing rate per upload"}})

        # Duration KPIs
        upl_seconds = parse_duration_to_seconds(df[CS_UPL_DUR]).sum()
        cre_seconds = parse_duration_to_seconds(df[CS_CRE_DUR]).sum()
        pub_seconds = parse_duration_to_seconds(df[CS_PUB_DUR]).sum()
        uploaded_hours = round(upl_seconds / 3600, 2)
        processed_hours = round(cre_seconds / 3600, 2)
        published_hours = round(pub_seconds / 3600, 2)
        avg_upload_min = round(upl_seconds / total_uploaded / 60, 2) if total_uploaded > 0 else 0

        metrics.append({{"id": "uploaded_hours", "name": "Uploaded Hours", "value": uploaded_hours,
                         "formatted": f"{{uploaded_hours}}h", "category": "duration",
                         "description": "Total duration of uploaded videos"}})
        metrics.append({{"id": "processed_hours", "name": "Processed Hours", "value": processed_hours,
                         "formatted": f"{{processed_hours}}h", "category": "duration",
                         "description": "Total duration of processed clips"}})
        metrics.append({{"id": "published_hours", "name": "Published Hours", "value": published_hours,
                         "formatted": f"{{published_hours}}h", "category": "duration",
                         "description": "Total duration of published clips"}})
        metrics.append({{"id": "avg_upload_min", "name": "Avg Upload Duration", "value": avg_upload_min,
                         "formatted": f"{{avg_upload_min}} min", "category": "duration",
                         "description": "Average duration per uploaded video"}})

        # Distinct channels
        distinct_channels = int(df[CS_CHANNEL].nunique())
        metrics.append({{"id": "distinct_channels", "name": "Distinct Channels", "value": distinct_channels,
                         "formatted": str(distinct_channels), "category": "volume",
                         "description": "Number of unique channels"}})

        # Top performing channel
        df_c = df.copy()
        df_c["_created_num"] = pd.to_numeric(df_c[CS_CREATED], errors="coerce")
        df_c["_published_num"] = pd.to_numeric(df_c[CS_PUBLISHED], errors="coerce")
        df_c["_pr"] = df_c["_published_num"] / df_c["_created_num"].replace(0, float("nan"))
        valid = df_c.dropna(subset=["_pr"])
        if len(valid) > 0:
            top_row = valid.loc[valid["_pr"].idxmax()]
            top_ch = str(top_row[CS_CHANNEL])
            top_rate = round(float(top_row["_pr"] * 100), 2)
            metrics.append({{"id": "top_performing_channel", "name": "Top Channel", "value": top_ch,
                             "formatted": f"{{top_ch}} ({{top_rate}}%)", "category": "conversion",
                             "description": "Channel with highest publish rate"}})

    # ─── Load user_summary for distinct users ─────────────────────────
    us_path = DATASET_PATHS.get("user_summary")
    if us_path and Path(us_path).exists():
        df_u = pd.read_csv(us_path, encoding="utf-8-sig")
        distinct_users = int(df_u[US_USER].nunique())
        metrics.append({{"id": "distinct_users", "name": "Distinct Users", "value": distinct_users,
                         "formatted": str(distinct_users), "category": "volume",
                         "description": "Number of unique users"}})

    # ─── Load monthly for peak month ──────────────────────────────────
    mo_path = DATASET_PATHS.get("monthly")
    if mo_path and Path(mo_path).exists():
        df_m = pd.read_csv(mo_path, encoding="utf-8-sig")
        df_m["_upl_num"] = pd.to_numeric(df_m[MO_UPLOADED], errors="coerce")
        if len(df_m) > 0 and df_m["_upl_num"].sum() > 0:
            peak_row = df_m.loc[df_m["_upl_num"].idxmax()]
            peak_month = str(peak_row[MO_MONTH])
            peak_count = int(peak_row["_upl_num"])
            metrics.append({{"id": "peak_upload_month", "name": "Peak Upload Month", "value": peak_month,
                             "formatted": f"{{peak_month}} ({{peak_count:,}})", "category": "efficiency",
                             "description": "Month with highest upload volume"}})

    return metrics


if __name__ == "__main__":
    result = compute_kpis()
    print(json.dumps(result, indent=2, default=str))
'''
    return script


def generate_chart_data_script(column_mappings: Dict[str, Dict[str, str]], dataset_paths: Dict[str, str]) -> str:
    """
    Generate chart_data_script.py that produces JSON chart data for the frontend.
    """
    cs = column_mappings.get("channel_summary", {})
    mo = column_mappings.get("monthly", {})
    ot = column_mappings.get("output_type", {})
    it = column_mappings.get("input_type", {})
    cp = column_mappings.get("channel_platform", {})

    script = f'''#!/usr/bin/env python3
# AUTO-GENERATED by analytics_engine — {datetime.now().isoformat()}
# Produces chart data JSONs for frontend interactive charts.

import pandas as pd
import json
from pathlib import Path

DATASET_PATHS = {json.dumps(dataset_paths, indent=4)}
OUTPUT_DIR = Path({repr(str(SAVED_DIR.parent / "chart_data"))})
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ─── Column mappings ─────────────────────────────────────────────────────
CS_CHANNEL   = {repr(cs.get("channel_name", "Channel"))}
CS_UPLOADED  = {repr(cs.get("uploaded_count", "Uploaded Count"))}
CS_CREATED   = {repr(cs.get("created_count", "Created Count"))}
CS_PUBLISHED = {repr(cs.get("published_count", "Published Count"))}

MO_MONTH     = {repr(mo.get("month_label", "Month"))}
MO_UPLOADED  = {repr(mo.get("monthly_uploaded", "Total Uploaded"))}
MO_CREATED   = {repr(mo.get("monthly_created", "Total Created"))}
MO_PUBLISHED = {repr(mo.get("monthly_published", "Total Published"))}

OT_NAME      = {repr(ot.get("output_type_name", "Output Type"))}
OT_CREATED   = {repr(ot.get("created_count", "Created Count"))}

IT_NAME      = {repr(it.get("input_type_name", "Input Type"))}
IT_UPLOADED  = {repr(it.get("uploaded_count", "Uploaded Count"))}

CP_CHANNEL   = {repr(cp.get("channel_name", "Channels"))}

OUTPUT_TYPE_COLORS = ["#4F46E5", "#06B6D4", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#EC4899"]
INPUT_TYPE_COLORS = ["#4F46E5", "#06B6D4", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#EC4899", "#14B8A6", "#F97316", "#6366F1", "#D946EF", "#84CC16"]


def save_json(data, filename):
    path = OUTPUT_DIR / filename
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return str(path)


def generate_all_chart_data():
    results = {{}}

    # ─── Monthly Trends ───────────────────────────────────────────────
    mo_path = DATASET_PATHS.get("monthly")
    if mo_path and Path(mo_path).exists():
        df = pd.read_csv(mo_path, encoding="utf-8-sig")
        monthly_data = []
        for _, row in df.iterrows():
            upl = int(pd.to_numeric(row.get(MO_UPLOADED, 0), errors="coerce") or 0)
            cre = int(pd.to_numeric(row.get(MO_CREATED, 0), errors="coerce") or 0)
            pub = int(pd.to_numeric(row.get(MO_PUBLISHED, 0), errors="coerce") or 0)
            pr = round(pub / cre * 100, 2) if cre > 0 else 0
            month_str = str(row.get(MO_MONTH, "")).strip().strip('"')
            # Shorten month label for chart
            short_month = month_str.split(",")[0].strip() if "," in month_str else month_str
            monthly_data.append({{
                "month": short_month,
                "uploaded": upl,
                "created": cre,
                "published": pub,
                "publishRate": pr
            }})
        results["monthly_trends"] = monthly_data
        save_json(monthly_data, "monthly_trends.json")

    # ─── Channel Performance ──────────────────────────────────────────
    cs_path = DATASET_PATHS.get("channel_summary")
    if cs_path and Path(cs_path).exists():
        df = pd.read_csv(cs_path, encoding="utf-8-sig")
        channel_data = []
        for _, row in df.iterrows():
            upl = int(pd.to_numeric(row.get(CS_UPLOADED, 0), errors="coerce") or 0)
            cre = int(pd.to_numeric(row.get(CS_CREATED, 0), errors="coerce") or 0)
            pub = int(pd.to_numeric(row.get(CS_PUBLISHED, 0), errors="coerce") or 0)
            rate = round(pub / cre * 100, 2) if cre > 0 else 0
            amp = round(cre / upl, 2) if upl > 0 else 0
            channel_data.append({{
                "name": f"Channel {{row.get(CS_CHANNEL, '')}}",
                "uploaded": upl,
                "created": cre,
                "published": pub,
                "rate": rate,
                "amp": amp
            }})
        # Sort by uploaded desc, take top channels
        channel_data.sort(key=lambda x: x["uploaded"], reverse=True)
        results["channel_performance"] = channel_data
        save_json(channel_data, "channel_performance.json")

        # ─── Funnel Data ──────────────────────────────────────────────
        total_upl = sum(c["uploaded"] for c in channel_data)
        total_cre = sum(c["created"] for c in channel_data)
        total_pub = sum(c["published"] for c in channel_data)
        funnel = [
            {{"stage": "Uploaded", "value": total_upl}},
            {{"stage": "Processed", "value": total_cre}},
            {{"stage": "Published", "value": total_pub}}
        ]
        results["funnel_data"] = funnel
        save_json(funnel, "funnel_data.json")

    # ─── Output Type Mix ──────────────────────────────────────────────
    ot_path = DATASET_PATHS.get("output_type")
    if ot_path and Path(ot_path).exists():
        df = pd.read_csv(ot_path, encoding="utf-8-sig")
        ot_data = []
        for i, (_, row) in enumerate(df.iterrows()):
            val = int(pd.to_numeric(row.get(OT_CREATED, 0), errors="coerce") or 0)
            ot_data.append({{
                "name": str(row.get(OT_NAME, "")).strip().strip('"'),
                "value": val,
                "color": OUTPUT_TYPE_COLORS[i % len(OUTPUT_TYPE_COLORS)]
            }})
        ot_data.sort(key=lambda x: x["value"], reverse=True)
        results["output_type_mix"] = ot_data
        save_json(ot_data, "output_type_mix.json")

    # ─── Input Type Mix ───────────────────────────────────────────────
    it_path = DATASET_PATHS.get("input_type")
    if it_path and Path(it_path).exists():
        df = pd.read_csv(it_path, encoding="utf-8-sig")
        it_data = []
        for i, (_, row) in enumerate(df.iterrows()):
            val = int(pd.to_numeric(row.get(IT_UPLOADED, 0), errors="coerce") or 0)
            it_data.append({{
                "name": str(row.get(IT_NAME, "")).strip().strip('"'),
                "value": val,
                "color": INPUT_TYPE_COLORS[i % len(INPUT_TYPE_COLORS)]
            }})
        it_data.sort(key=lambda x: x["value"], reverse=True)
        results["input_type_mix"] = it_data
        save_json(it_data, "input_type_mix.json")

    # ─── Platform Distribution ────────────────────────────────────────
    cp_path = DATASET_PATHS.get("channel_platform")
    if cp_path and Path(cp_path).exists():
        df = pd.read_csv(cp_path, encoding="utf-8-sig")
        # Sum across all channels for each platform
        platform_cols = [c for c in df.columns if c != CP_CHANNEL]
        platform_data = []
        for col in platform_cols:
            total = int(pd.to_numeric(df[col], errors="coerce").sum())
            if total > 0:
                platform_data.append({{"name": col, "value": total}})
        platform_data.sort(key=lambda x: x["value"], reverse=True)
        results["platform_distribution"] = platform_data
        save_json(platform_data, "platform_distribution.json")

    return results


if __name__ == "__main__":
    result = generate_all_chart_data()
    print(json.dumps({{k: len(v) for k, v in result.items()}}, indent=2))
'''
    return script


def save_script(script_name: str, content: str) -> Path:
    """Save a generated script to disk."""
    SAVED_DIR.mkdir(parents=True, exist_ok=True)
    path = SAVED_DIR / script_name
    path.write_text(content, encoding="utf-8")
    logger.info(f"Saved script: {path}")
    return path


def update_manifest(scripts_generated: list, trigger: str) -> None:
    """Update the script manifest with metadata."""
    manifest = {}
    if MANIFEST_PATH.exists():
        try:
            manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass

    for script_name in scripts_generated:
        manifest[script_name] = {
            "generated_at": datetime.now().isoformat(),
            "trigger": trigger
        }

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def generate_all_scripts(
    column_mappings: Dict[str, Dict[str, str]],
    dataset_paths: Dict[str, str],
    trigger: str = "schema_change"
) -> Dict[str, Path]:
    """Generate all analytics scripts and save them."""
    scripts = {}

    # KPI script
    kpi_content = generate_kpi_script(column_mappings, dataset_paths)
    scripts["kpi_script.py"] = save_script("kpi_script.py", kpi_content)

    # Chart data script
    chart_content = generate_chart_data_script(column_mappings, dataset_paths)
    scripts["chart_data_script.py"] = save_script("chart_data_script.py", chart_content)

    # Update manifest
    update_manifest(list(scripts.keys()), trigger)

    logger.info(f"Generated {len(scripts)} scripts (trigger: {trigger})")
    return scripts
